version: "3.8"
services:
  arkcase:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - ark-case-network
#    depends_on:
#        - postgres
#  postgres:
#    image: postgres:latest
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: "mysecretpassword"
#      POSTGRES_DB: arkcase_db
#    container_name: postgres-db
#
#
#volumes:
#    postgres_data:
